import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-10 text-yellow-500 max-w-4xl m-auto`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
